#!/usr/bin/env bash
# This script forcibly kills the 7-highlander process using SIGKILL

# Find the PID(s) of the 7-highlander process
pid=$(pgrep -f "7-highlander")

# If a PID was found, send SIGKILL
if [ -n "$pid" ]; then
    kill -9 "$pid"
fi
